export const LOGIN_USER = "LOGIN_USER";
export const SET_LOADING = "SET_LOADING";
export const ADD_USER_TO_LOCALSTORAGE = "ADD_USER_TO_LOCALSTORAGE";
export const REMOVE_USER_FROM_LOCALSTORAGE = "REMOVE_USER_FROM_LOCALSTORAGE";
export const GET_USER_FROM_LOCALSTORAGE = "GET_USER_FROM_LOCALSTORAGE";
