// Auth reducer types
export const LOGIN_USER = "LOGIN_USER";
export const SET_LOADING = "SET_LOADING";
export const ADD_USER_TO_LOCALSTORAGE = "ADD_USER_TO_LOCALSTORAGE";
export const REMOVE_USER_FROM_LOCALSTORAGE = "REMOVE_USER_FROM_LOCALSTORAGE";
export const GET_USER_FROM_LOCALSTORAGE = "GET_USER_FROM_LOCALSTORAGE";
export const LOGOUT_USER = "LOGOUT_USER";
export const USER_LOADING = "USER_LOADING";

// Dashboard reducer types
export const SET_DASHBOARD_CONTENT_NAME = "SET_DASHBOARD_CONTENT_NAME";
