export const LOGIN = "LOGIN";
export const UPDATE_LOGIN_PAGE = "UPDATE_LOGIN_PAGE";
export const HANDLE_REMEMBER = "HANDLE_REMEMBER";
export const HANDLE_LOGIN_ALERT = "HANDLE_LOGIN_ALERT";
export const RESET_CREDENTIALS = "RESET_CREDENTIALS";
