export const LOGIN = "LOGIN";
export const UPDATE_LOGIN_PAGE = "UPDATE_LOGIN_PAGE";
export const HANDLE_REMEMBER = "HANDLE_REMEMBER";
export const HANDLE_LOGIN_ALERT = "HANDLE_LOGIN_ALERT";
export const RESET_CREDENTIALS = "RESET_CREDENTIALS";
export const UPDATE_REGISTER_PAGE = "UPDATE_REGISTER_PAGE";
export const CHECK_REGISTER_INFO = "CHECK_REGISTER_INFO";
export const REGISTER = "REGISTER";
